<script type="text/javascript" src="http://cdn.zfcyc.com/jquery/1.11.1/jquery.min.js"></script>
<script type="text/javascript" src="http://cdn.zfcyc.com/vue/2.4.2/vue.min.js"></script>
<script type="text/javascript" src="http://cdn.zfcyc.com/uikit/v3.0.0-rc.24/js/uikit.min.js"></script>
<script type="text/javascript" src="http://cdn.zfcyc.com/uikit/v3.0.0-rc.24/js/uikit-icons.min.js"></script>
<script type="text/javascript" src="http://cdn.zfcyc.com/vue-resource/1.3.4/vue-resource.min.js"></script>
<script type="text/javascript" src="http://cdn.zfcyc.com/moment.js/2.22.2/moment.min.js"></script>
<script type="text/javascript" src="http://cdn.zfcyc.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/${themeName}/source/js/global.js"></script>
<script type="text/javascript" src="/${themeName}/source/js/main.js"></script>